import ProjectDescription

let workspace = Workspace(
    name: "MoodMonitor",
    projects: [".", "Modules/**"],
    schemes: [],
    additionalFiles: [],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
